highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://tholzschuh.github.io/uni
author: Tim Holzschuh

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /cv/
title: Tim Holzschuh's Resume
name: Tim Holzschuh
email: t.holzschuh
email_full: t.holzschuh@stud.uni-heidelberg.de
website: tholzschuh.github.io
website_full: https://tholzschuh.github.io/
github: tholzschuh
stackexchange: users/499195/lush
#twitter: twitter
#tel: +49 0000 000000
#tel_full: tel:+440000000000
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: Brombacher Str. 68
  postcode: 69434
  city: Eberbach
  country: Germany
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
